[platformio]
default_envs = esp32s3_n16r8
src_dir = main
build_dir = .pio/build

[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
extra_scripts = pre:scripts/set_component_cache.py
lib_ldf_mode = chain+
build_flags =
  -DCHIP_HAVE_CONFIG_H
  '-DCHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME="Zafiro"'
  '-DCHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME="ROEHN Matter Bridge"'
  -DCHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION=1

[env:esp32c6_n16]
board = esp32-c6-devkitc-1
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
  ${env.build_flags}
  '-DCHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING="ESP32-C6 DevKitC-1 16MB"'

[env:esp32s3_n16r8]
board = esp32-s3-devkitc-1
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
  ${env.build_flags}
  '-DCHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING="ESP32-S3 DevKitC-1 N16R8 16MB+8MBPSRAM"'
  -I"${PROJECT_DIR}/managed_components/espressif__esp_matter/connectedhomeip/connectedhomeip/zzz_generated/app-common"
